# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/UART_DATA_FIFO/UART_DATA_FIFO.xci
# IP: The module: 'UART_DATA_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/UART_DATA_FIFO/UART_DATA_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DATA_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/UART_DATA_FIFO/UART_DATA_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/UART_DATA_FIFO/UART_DATA_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/UART_DATA_FIFO/UART_DATA_FIFO.xci
# IP: The module: 'UART_DATA_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/UART_DATA_FIFO/UART_DATA_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/UART_DATA_FIFO/UART_DATA_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/UART_DATA_FIFO/UART_DATA_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_DATA_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
