# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Robot.xdc

# IP: ip/DJ_DATA_ROM/DJ_DATA_ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DJ_DATA_ROM || ORIG_REF_NAME==DJ_DATA_ROM} -quiet] -quiet

# XDC: ip/DJ_DATA_ROM/DJ_DATA_ROM_ooc.xdc
