# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/clk_10M/clk_10M.xci
# IP: The module: 'clk_10M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/clk_10M/clk_10M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/clk_10M/clk_10M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/clk_10M/clk_10M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/clk_10M/clk_10M.xci
# IP: The module: 'clk_10M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/clk_10M/clk_10M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/clk_10M/clk_10M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Robot2.15h/Robot2.00.srcs/sources_1/ip/clk_10M/clk_10M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_10M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
